### ISSUE TITLE
District Level Stats on "Thank you for calling page"

### ISSUE THREAD

**Issue by boralben** [project-grand-canyon/pgc-public#7]
To encourage our callers to keep it up...

Use the new `/stats/$district_id` endpoint to display call-in stats about the caller's district on the thank you for calling page. Particularly the number of callers and calls by people in the district. Potentially show and up and to the right graph of cumulative calls since the project started.

Ben

**Comment by DrDoorknob** [comment]
I've made a start on this since it takes me through the whole main workflow of the app, but I've run into a snag. Trying to save a Call (I called!) is resulting in a 500 server error. I haven't really set up a Java debugging environment, and my console isn't showing any information, so I may be reliant on others for the moment to figure out what's going wrong (Or, give me some recommendations for running a debug server)

**Comment by boralben** [comment]
I tried to reproduce this. I could not get the API to 500 when clicking "I Called!"

I wonder if it's a content seeding issue. Have you locally created the below?
- a district
- a caller
- talking points (and associated the district script with them)

Any extra info you can include about your setup will help to diagnose.
